// user action
export const GET_INFO_USER_REQ = 'GET_INFO_USER_REQ';
export const GET_INFO_USER_SUCCESS = 'GET_INFO_USER_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// room action
export const GET_LIST_ROOM_REQ = 'GET_LIST_ROOM_REQ';
export const GET_DETAIL_ROOM_REQ = 'GET_DETAIL_ROOM_REQ';
export const GET_DETAIL_ROOM_SUCCESS = 'GET_DETAIL_ROOM_SUCCESS';
export const GET_LIST_ROOM_SUCCESS = 'GET_LIST_ROOM_SUCCESS';
export const SELECT_ROOM = 'SELECT_ROOM';


// message action
export const GET_LIST_MESSAGE_REQ = 'GET_LIST_MESSAGE_REQ';
export const GET_LIST_MESSAGE_SUCCESS = 'GET_LIST_MESSAGE_SUCCESS';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const RECEIVE_MESSAGE_SUCCESS = 'RECEIVE_MESSAGE_SUCCESS';
export const CLEAR_LIST_MESSAGE = 'CLEAR_LIST_MESSAGE';

